services:
  identityapi:
    image: sunbros/identityapi
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=UserTest;Username=postgres;Password=qe13zc24680
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Admin123
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - C:\Users\shuks\RiderProjects\ArtsoftMicroServices\Artsoft\IdentityApi\IdentityApi\ASP.Net:/home/app/.aspnet/https 

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: UserTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qe13zc24680
    ports:
      - "5432:5432"